from datetime import datetime

def format_report_header(symbol):
    return f"{symbol.upper()} – Technical & Fundamental Snapshot\n(Generated on current market data)\n"

def format_report_footer():
    return (
        "\nReport generated by Rushhabh Stock Bot.\n"
        "For educational & analysis purposes only."
    )
